post:
  summary: 拉取导购相关属性（敏感词等）
  security:
    - accessToken: []
  tags:
    - 导购助手∙账号属性设置
  parameters:
    - in: body
      name: body
      schema:
        type: object
        required:
          - guide_account
        properties:
          guide_account:
            type: string
            description: 导购微信号
  responses:
    '200':
      description: ''
      schema:
        allOf:
          - $ref: '#/definitions/base.ResponseBo'
          - type: object
            properties:
              guide_fast_reply_list:
                type: array
                items:
                  type: object
                  properties:
                    msgtype:
                      type: integer
                      format: int32
                    content:
                      type: string
                      description: 快捷回复内容
                    updatetime:
                      type: integer
                      format: int32
              guide_auto_reply:
                type: object
                properties:
                  msgtype:
                    type: integer
                    format: int32
                  content:
                    type: string
                    description: 自动回复内容
                  updatetime:
                    type: integer
                    format: int32
              updatetime:
                type: integer
                format: int32
