post:
  summary: 小程序插件管理权限集
  description: 插件管理权限集用于第三方代小程序管理插件，具体包括：添加插件、查询已添加的插件及删除插件。[官方文档](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=21521637082Sqi4M)
  operationId: wxa/plugin
  security:
    - authorizerAccessToken: []
  tags:
    - 开放平台/第三方平台/代小程序
  parameters:
    - in: body
      name: body
      schema:
        type: object
        properties:
          action:
            type: string
            description: apply=申请使用插件接口;list=查询已添加的插件;unbind=删除已添加的插件
            enum: ['apply', 'list', 'unbind']
          plugin_appid:
            type: string
            description: 插件appid
        required:
          - action
  responses:
    '200':
      description: ''
      schema:
        allOf:
          - $ref: '#/definitions/base.ResponseBo'
          - type: object
            description: 查询已添加的插件时返回
            properties:
              plugin_list:
                type: array
                items:
                  type: object
                  properties:
                    appid:
                      type: string
                      description: 插件appid
                    status:
                      type: integer
                      format: int32
                      description: 插件状态（1：申请中，2：申请通过，3：被拒绝；4：已超时）
                      enum: [1, 2, 3, 4]
                    nickname:
                      type: string
                      description: 插件昵称
                    headimgurl:
                      type: string
                      description: 插件头像
