post:
  x-api-cert-required: true
  tags:
    - 支付∙服务商∙小微商户
    - 支付∙银行服务商∙特约商户配置
  summary: 配置查询
  description: 服务商给特约子商户配置推荐关注、绑定关系和配置支付目录后可调用该API查询。[官方文档](https://pay.weixin.qq.com/wiki/doc/api/mch_bank.php?chapter=9_25&index=4&p=901)
  consumes:
    - application/xml
  produces:
    - application/xml
  parameters:
    - name: buffer
      in: body
      required: true
      schema:
        $ref: 'wxpay.yaml#/querysubdevconfig.request'
  responses:
    '200':
      description: ''
      schema:
        $ref: 'wxpay.yaml#/querysubdevconfig.response'
