addsubdevconfig.request:
  allOf:
    - type: object
      xml:
        name: xml
      properties: {}
addsubdevconfig.response:
  allOf:
    - type: object
      xml:
        name: xml
      properties: {}
