querysubdevconfig.request:
  allOf:
    - type: object
      xml:
        name: xml
      properties: {}
querysubdevconfig.response:
  allOf:
    - type: object
      xml:
        name: xml
      properties: {}
